// Auto-generated by notebook-to-lib

// Cell metadata for targeting (used by mount())
export const cells = [
  {
    "id": 1,
    "index": 0,
    "names": [
      "one",
      "cell:0"
    ],
    "inputs": [
      "Inputs"
    ],
    "outputs": [
      "viewof one"
    ],
    "isView": true
  },
  {
    "id": 2,
    "index": 1,
    "names": [
      "other",
      "cell:1"
    ],
    "inputs": [
      "Inputs"
    ],
    "outputs": [
      "viewof other"
    ],
    "isView": true
  },
  {
    "id": 3,
    "index": 2,
    "names": [
      "out",
      "cell:2"
    ],
    "inputs": [
      "one",
      "other"
    ],
    "outputs": [
      "out"
    ],
    "isView": false
  }
];

export default function define(runtime, observer) {
  const main = runtime.module();
  const _1 = (Inputs) => {
const one = (Inputs.text({label: "Text 1", value: "Hello World"}));
({ one })
return {one};
};
  main.variable(observer("viewof one")).define("viewof one", ["Inputs"], (...args) => Promise.resolve(_1(...args)).then((o) => (o && typeof o === "object" && "one" in o) ? o["one"] : o));
  main.variable(observer("one")).define("one", ["Generators", "viewof one"], (G, _) => G.input(_));
  const _2 = (Inputs) => {
const other = (Inputs.text({label: "Text 2", value: "Hello Observable"}));
({ other })
return {other};
};
  main.variable(observer("viewof other")).define("viewof other", ["Inputs"], (...args) => Promise.resolve(_2(...args)).then((o) => (o && typeof o === "object" && "other" in o) ? o["other"] : o));
  main.variable(observer("other")).define("other", ["Generators", "viewof other"], (G, _) => G.input(_));
  const _3 = async (one,other) => {
const {diff_match_patch} = await import("diff-match-patch").then((module) => {
  if (!("diff_match_patch" in module)) throw new SyntaxError(`export 'diff_match_patch' not found`);
  return module;
});

const dmp = new diff_match_patch();
const diffs = dmp.diff_main(one, other);
dmp.diff_cleanupSemantic(diffs);

const diffHtml = diffs.map(([op, text]) => {
  const color = op === 1 ? 'green' : op === -1 ? 'red' : 'black';
  const bg = op === 1 ? '#e6ffe6' : op === -1 ? '#ffe6e6' : 'transparent';
  return `<span style="color: ${color}; background: ${bg}; padding: 2px 4px;">${text}</span>`;
}).join('');

const out = document.createElement('div');
out.style.fontFamily = 'monospace';
out.style.padding = '10px';
out.innerHTML = diffHtml;

void (out);
return {diff_match_patch,dmp,diffs,diffHtml,out};
};
  main.variable(observer("out")).define("out", ["one","other"], (...args) => Promise.resolve(_3(...args)).then((o) => (o && typeof o === "object" && "out" in o) ? o["out"] : o));
  return main;
}